# Generated by Django 6.0.2 on 2026-02-10 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_roll_no_studentprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
    ]
